use_frameworks!

target 'FRLocalization_Example' do
  pod 'FRLocalization', :path => '../'

  target 'FRLocalization_Tests' do
    pod 'FRLocalization', :path => '../'
    inherit! :search_paths

    
  end
end
